drop database if exists SQL_LAB_CAR;

CREATE DATABASE IF NOT EXISTS SQL_LAB_CAR;
USE SQL_LAB_CAR;
CREATE TABLE CARS (
	VIN VARCHAR(30) PRIMARY KEY,
	MANUFACTURER VARCHAR (30),
    MODEL VARCHAR (30), 
    YEAR YEAR, 
    COLOUR VARCHAR (30)
    );
    
CREATE TABLE INVOICES (
	INVOICE_NUMBER INT PRIMARY KEY,
    DATE DATE,
    CAR VARCHAR (30),
    CUSTOMER INT, 
    SALESPERSON int
    );

CREATE TABLE SALESPERSONS (
	STAFF_ID INT PRIMARY KEY,
    NAME VARCHAR (30), 
    STORE VARCHAR (30)
    );

CREATE TABLE CUSTOMERS (
	CUSTOMER_ID INT PRIMARY KEY,
	NAME VARCHAR (30), 
    PHONE_NUMBER VARCHAR(50),
    E_MAIL VARCHAR (30), 
    ADDRESS VARCHAR (30), 
    CITY VARCHAR (30), 
    STATE VARCHAR (30), 
    COUNTRY VARCHAR (30),
    POSTAL_CODE VARCHAR (30)
    ); 


ALTER TABLE INVOICES
	ADD FOREIGN KEY (CAR) 
REFERENCES CARS(VIN) 
ON DELETE CASCADE;

ALTER TABLE INVOICES
	ADD FOREIGN KEY (SALESPERSON) 
REFERENCES SALESPERSONS(STAFF_ID) 
ON DELETE CASCADE;

ALTER TABLE INVOICES
	ADD FOREIGN KEY (CUSTOMER) 
REFERENCES CUSTOMERS(CUSTOMER_ID) 
ON DELETE CASCADE;
    
    
    
    



    
    
    









